#pragma once
//ENUMERATIONS
enum shader_enum { OBJ = 0, SKY_BOXD4, WALLD4, DEMOD4,EMITD4, TERRAIND4, WATERD4, PARTICLE4D, COORDNATE4D, TRAIL4D, JOINT_LINE4D, FRAME4D, LIGHT_FRAME4D ,ATOMOSPHERE };
enum shader_hdr_enum { HDR = 0,HDR_EXPOSURE, SUB,SUB_EXPOSURE, MIP, BLOOM };
enum texture_enum { TEX_SKY_BOX = 0, TEX_1, TEX_1_SPECULAR, TEX_2, TEX_2_SPECULAR };
enum texture3d_enum {
	TEX_NOISE_3D = 0,TEX_STARS_FIELD_3D, TEX_NORMAL_4D, CAUSTICS, BLEND,AREA
};
enum particle4d_enum {
	FIRE=0,PARTICLE1, PARTICLE2, PARTICLE3
};
enum wall4d_enum {
	PURE_RED = 0, PURE_RED_HARFGREEN, PURE_RED_GREEN, PURE_HARFRED_GREEN, PURE_GREEN,
	PURE_GREEN_HARFBLUE, PURE_GREEN_BLUE, PURE_HARFGREEN_BLUE, PURE_BLUE, PURE_HARFRED_BLUE, PURE_RED_BLUE, PURE_RED_HARFBLUE,
	PURE_WHITE, PURE_BLACK,

	STONE, WHITE, YELLOW, GROUND,
	C1, C2, C_2,C3, C4, C5, GRID2, C6, CHESSBOARD, WHITEWALL,
	GREENMARBLE, WHITEMARBLE, YELLOWMARBLE, MARBLE_GROUND,DEFAULTCHESSBOARD,
	MARBLE_C1, MARBLE_C2, MARBLE_C3, MARBLE_C4, MARBLE_C5, MARBLE_C6, CHESSBOARDMARBLE, WHITEMAINMARBLE,
	CONCRETE, YELLOWCONCRETE, WHITECONCRETE,
	GRASS, WOODX, WOODY, WOODZ,OLDWOODX,OLDWOODY,OLDWOODZ, GLASS,GRID, STARS, STARS_SKY,
	CEIL1, CEIL2
};
enum ground4d_enum {
	SAND = 0, SNOW, ICE, GRASS1, GRASS2, SOIL, GRASS3, GRASS4, SAND_SOIL, SAND_SOIL2,
	SANDH, SNOWH, ICEH, GRASS1H, GRASS2H, SOILH, GRASS3H, GRASS4H, SAND_SOILH, SAND_SOIL2H
};
enum collider_enum { NONE = 0, BOX4D, STEP4D, SPHERE4D, MESH4D, CAPSULE4D, TERRAIN4D, WATER4D };
enum mesh_enum { HYPERCUBE=0, HYPERSPHERE, HYPERCAPSULE,HYPERCYLINDER, HYPERCONE, HYPERPOT, TRIPRISM, HYPERSLOPE, HYPERQUAD, PENTACHORON,HYPERPYRAMID, HEXADECACHORON, HEXACOSICHORON};
enum trail_enum { FORGET = 0 ,LINEAR, INVARIBLE};
enum mode_enum { SHOOTING = 0,CONTROLING,PAINTING,BUILDING,DELETING, AREA_DELETING};
enum buildmode_enum { BUILD_OBJECT=0, BUILD_RIGIDBODY, BUILD_POOL_TABLE, BUILD_BILLIARD,BUILD_DYNAMITE, BUILD_STICK, BUILD_SPRING };