#pragma once
#define GLEW_STATIC
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <sstream>
#include <algorithm>
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm.hpp>
#include <vec2.hpp>
#include <vec3.hpp>
#include <vec4.hpp>
#include <mat4x4.hpp>
#include <gtc\matrix_transform.hpp>
#include <gtc\type_ptr.hpp>
#include <SOIL2.h>
#include <SFML/Audio.hpp>
#include "mod.h"
#include "EnumLists.h"

#include "Vertex.h"
#include "Primitives.h"
#include "Shader.h"
#include "Texture.h"
#include "Sound.h"
#include "Line.h"
#include "OBJLoader.h"
#include "Shape2D.h"
#include "GetWindowSize.h"
#include "Input.h"
#include "InputLists.h"
#include "Mesh.h"
#include "Light.h"
#include "Particle4D.h"
#include "Object.h"
#include "body.h"
#include "Camera.h"
#include "Controller.h"
#include "Group.h"
#include "Joint.h"
#include "Demo.h"
#include "ObjectLists.h"
#include "FixedUpdate.h"
#include "Phys4D.h"
#include "DetectRay.h"
#include "Animation.h"
#include "LoadAndSave.h"

